spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: zg1967
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
#create-drop